#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""Planets data file."""


def get_planets_data():
    """Get planets data."""
    data = [{'climate': 'arid',
             'diameter': '10465',
             'gravity': '1 standard',
             'name': 'Tatooine',
             'orbital_period': '304',
             'population': '200000',
             'residents': ['http://swapi.co/api/people/1/',
                           'http://swapi.co/api/people/2/',
                           'http://swapi.co/api/people/4/',
                           'http://swapi.co/api/people/6/',
                           'http://swapi.co/api/people/7/',
                           'http://swapi.co/api/people/8/',
                           'http://swapi.co/api/people/9/',
                           'http://swapi.co/api/people/11/',
                           'http://swapi.co/api/people/43/',
                           'http://swapi.co/api/people/62/'],
             'rotation_period': '23',
             'surface_water': '1',
             'terrain': 'desert'},
            {'climate': 'temperate',
             'diameter': '12500',
             'gravity': '1 standard',
             'name': 'Alderaan',
             'orbital_period': '364',
             'population': '2000000000',
             'residents': ['http://swapi.co/api/people/5/',
                           'http://swapi.co/api/people/68/',
                           'http://swapi.co/api/people/81/'],
             'rotation_period': '24',
             'surface_water': '40',
             'terrain': 'grasslands, mountains'},
            {'climate': 'temperate, tropical',
             'diameter': '10200',
             'gravity': '1 standard',
             'name': 'Yavin IV',
             'orbital_period': '4818',
             'population': '1000',
             'residents': [],
             'rotation_period': '24',
             'surface_water': '8',
             'terrain': 'jungle, rainforests'},
            {'climate': 'frozen',
             'diameter': '7200',
             'gravity': '1.1 standard',
             'name': 'Hoth',
             'orbital_period': '549',
             'population': 'unknown',
             'residents': [],
             'rotation_period': '23',
             'surface_water': '100',
             'terrain': 'tundra, ice caves, mountain ranges'},
            {'climate': 'murky',
             'diameter': '8900',
             'gravity': 'N/A',
             'name': 'Dagobah',
             'orbital_period': '341',
             'population': 'unknown',
             'residents': [],
             'rotation_period': '23',
             'surface_water': '8',
             'terrain': 'swamp, jungles'},
            {'climate': 'temperate',
             'diameter': '118000',
             'gravity': '1.5 (surface), 1 standard (Cloud City)',
             'name': 'Bespin',
             'orbital_period': '5110',
             'population': '6000000',
             'residents': ['http://swapi.co/api/people/26/'],
             'rotation_period': '12',
             'surface_water': '0',
             'terrain': 'gas giant'},
            {'climate': 'temperate',
             'diameter': '4900',
             'gravity': '0.85 standard',
             'name': 'Endor',
             'orbital_period': '402',
             'population': '30000000',
             'residents': ['http://swapi.co/api/people/30/'],
             'rotation_period': '18',
             'surface_water': '8',
             'terrain': 'forests, mountains, lakes'},
            {'climate': 'temperate',
             'diameter': '12120',
             'gravity': '1 standard',
             'name': 'Naboo',
             'orbital_period': '312',
             'population': '4500000000',
             'residents': ['http://swapi.co/api/people/3/',
                           'http://swapi.co/api/people/21/',
                           'http://swapi.co/api/people/36/',
                           'http://swapi.co/api/people/37/',
                           'http://swapi.co/api/people/38/',
                           'http://swapi.co/api/people/39/',
                           'http://swapi.co/api/people/42/',
                           'http://swapi.co/api/people/60/',
                           'http://swapi.co/api/people/61/',
                           'http://swapi.co/api/people/66/',
                           'http://swapi.co/api/people/35/'],
             'rotation_period': '26',
             'surface_water': '12',
             'terrain': 'grassy hills, swamps, forests, mountains'},
            {'climate': 'temperate',
             'diameter': '12240',
             'gravity': '1 standard',
             'name': 'Coruscant',
             'orbital_period': '368',
             'population': '1000000000000',
             'residents': ['http://swapi.co/api/people/34/',
                           'http://swapi.co/api/people/55/',
                           'http://swapi.co/api/people/74/'],
             'rotation_period': '24',
             'surface_water': 'unknown',
             'terrain': 'cityscape, mountains'},
            {'climate': 'temperate',
             'diameter': '19720',
             'gravity': '1 standard',
             'name': 'Kamino',
             'orbital_period': '463',
             'population': '1000000000',
             'residents': ['http://swapi.co/api/people/22/',
                           'http://swapi.co/api/people/72/',
                           'http://swapi.co/api/people/73/'],
             'rotation_period': '27',
             'surface_water': '100',
             'terrain': 'ocean'},
            {'climate': 'temperate, arid',
             'diameter': '11370',
             'gravity': '0.9 standard',
             'name': 'Geonosis',
             'orbital_period': '256',
             'population': '100000000000',
             'residents': ['http://swapi.co/api/people/63/'],
             'rotation_period': '30',
             'surface_water': '5',
             'terrain': 'rock, desert, mountain, barren'},
            {'climate': 'temperate, arid, windy',
             'diameter': '12900',
             'gravity': '1 standard',
             'name': 'Utapau',
             'orbital_period': '351',
             'population': '95000000',
             'residents': ['http://swapi.co/api/people/83/'],
             'rotation_period': '27',
             'surface_water': '0.9',
             'terrain': 'scrublands, savanna, canyons, sinkholes'},
            {'climate': 'hot',
             'diameter': '4200',
             'gravity': '1 standard',
             'name': 'Mustafar',
             'orbital_period': '412',
             'population': '20000',
             'residents': [],
             'rotation_period': '36',
             'surface_water': '0',
             'terrain': 'volcanoes, lava rivers, mountains, caves'},
            {'climate': 'tropical',
             'diameter': '12765',
             'gravity': '1 standard',
             'name': 'Kashyyyk',
             'orbital_period': '381',
             'population': '45000000',
             'residents': ['http://swapi.co/api/people/13/',
                           'http://swapi.co/api/people/80/'],
             'rotation_period': '26',
             'surface_water': '60',
             'terrain': 'jungle, forests, lakes, rivers'},
            {'climate': 'artificial temperate ',
             'diameter': '0',
             'gravity': '0.56 standard',
             'name': 'Polis Massa',
             'orbital_period': '590',
             'population': '1000000',
             'residents': [],
             'rotation_period': '24',
             'surface_water': '0',
             'terrain': 'airless asteroid'},
            {'climate': 'frigid',
             'diameter': '10088',
             'gravity': '1 standard',
             'name': 'Mygeeto',
             'orbital_period': '167',
             'population': '19000000',
             'residents': [],
             'rotation_period': '12',
             'surface_water': 'unknown',
             'terrain': 'glaciers, mountains, ice canyons'},
            {'climate': 'hot, humid',
             'diameter': '9100',
             'gravity': '0.75 standard',
             'name': 'Felucia',
             'orbital_period': '231',
             'population': '8500000',
             'residents': [],
             'rotation_period': '34',
             'surface_water': 'unknown',
             'terrain': 'fungus forests'},
            {'climate': 'temperate, moist',
             'diameter': '0',
             'gravity': '1 standard',
             'name': 'Cato Neimoidia',
             'orbital_period': '278',
             'population': '10000000',
             'residents': ['http://swapi.co/api/people/33/'],
             'rotation_period': '25',
             'surface_water': 'unknown',
             'terrain': 'mountains, fields, forests, rock arches'},
            {'climate': 'hot',
             'diameter': '14920',
             'gravity': 'unknown',
             'name': 'Saleucami',
             'orbital_period': '392',
             'population': '1400000000',
             'residents': [],
             'rotation_period': '26',
             'surface_water': 'unknown',
             'terrain': 'caves, desert, mountains, volcanoes'},
            {'climate': 'temperate',
             'diameter': '0',
             'gravity': '1 standard',
             'name': 'Stewjon',
             'orbital_period': 'unknown',
             'population': 'unknown',
             'residents': ['http://swapi.co/api/people/10/'],
             'rotation_period': 'unknown',
             'surface_water': 'unknown',
             'terrain': 'grass'},
            {'climate': 'polluted',
             'diameter': '13490',
             'gravity': '1 standard',
             'name': 'Eriadu',
             'orbital_period': '360',
             'population': '22000000000',
             'residents': ['http://swapi.co/api/people/12/'],
             'rotation_period': '24',
             'surface_water': 'unknown',
             'terrain': 'cityscape'},
            {'climate': 'temperate',
             'diameter': '11000',
             'gravity': '1 standard',
             'name': 'Corellia',
             'orbital_period': '329',
             'population': '3000000000',
             'residents': ['http://swapi.co/api/people/14/',
                           'http://swapi.co/api/people/18/'],
             'rotation_period': '25',
             'surface_water': '70',
             'terrain': 'plains, urban, hills, forests'},
            {'climate': 'hot',
             'diameter': '7549',
             'gravity': '1 standard',
             'name': 'Rodia',
             'orbital_period': '305',
             'population': '1300000000',
             'residents': ['http://swapi.co/api/people/15/'],
             'rotation_period': '29',
             'surface_water': '60',
             'terrain': 'jungles, oceans, urban, swamps'},
            {'climate': 'temperate',
             'diameter': '12150',
             'gravity': '1 standard',
             'name': 'Nal Hutta',
             'orbital_period': '413',
             'population': '7000000000',
             'residents': ['http://swapi.co/api/people/16/'],
             'rotation_period': '87',
             'surface_water': 'unknown',
             'terrain': 'urban, oceans, swamps, bogs'},
            {'climate': 'temperate',
             'diameter': '9830',
             'gravity': '1 standard',
             'name': 'Dantooine',
             'orbital_period': '378',
             'population': '1000',
             'residents': [],
             'rotation_period': '25',
             'surface_water': 'unknown',
             'terrain': 'oceans, savannas, mountains, grasslands'},
            {'climate': 'temperate',
             'diameter': '6400',
             'gravity': 'unknown',
             'name': 'Bestine IV',
             'orbital_period': '680',
             'population': '62000000',
             'residents': ['http://swapi.co/api/people/19/'],
             'rotation_period': '26',
             'surface_water': '98',
             'terrain': 'rocky islands, oceans'},
            {'climate': 'temperate',
             'diameter': '14050',
             'gravity': '1 standard',
             'name': 'Ord Mantell',
             'orbital_period': '334',
             'population': '4000000000',
             'residents': [],
             'rotation_period': '26',
             'surface_water': '10',
             'terrain': 'plains, seas, mesas'},
            {'climate': 'unknown',
             'diameter': '0',
             'gravity': 'unknown',
             'name': 'unknown',
             'orbital_period': '0',
             'population': 'unknown',
             'residents': ['http://swapi.co/api/people/20/',
                           'http://swapi.co/api/people/23/',
                           'http://swapi.co/api/people/29/',
                           'http://swapi.co/api/people/32/',
                           'http://swapi.co/api/people/75/',
                           'http://swapi.co/api/people/84/',
                           'http://swapi.co/api/people/85/',
                           'http://swapi.co/api/people/86/',
                           'http://swapi.co/api/people/87/',
                           'http://swapi.co/api/people/88/'],
             'rotation_period': '0',
             'surface_water': 'unknown',
             'terrain': 'unknown'},
            {'climate': 'arid',
             'diameter': '0',
             'gravity': '0.62 standard',
             'name': 'Trandosha',
             'orbital_period': '371',
             'population': '42000000',
             'residents': ['http://swapi.co/api/people/24/'],
             'rotation_period': '25',
             'surface_water': 'unknown',
             'terrain': 'mountains, seas, grasslands, deserts'},
            {'climate': 'arid',
             'diameter': '0',
             'gravity': '1 standard',
             'name': 'Socorro',
             'orbital_period': '326',
             'population': '300000000',
             'residents': ['http://swapi.co/api/people/25/'],
             'rotation_period': '20',
             'surface_water': 'unknown',
             'terrain': 'deserts, mountains'},
            {'climate': 'temperate',
             'diameter': '11030',
             'gravity': '1',
             'name': 'Mon Cala',
             'orbital_period': '398',
             'population': '27000000000',
             'residents': ['http://swapi.co/api/people/27/'],
             'rotation_period': '21',
             'surface_water': '100',
             'terrain': 'oceans, reefs, islands'},
            {'climate': 'temperate',
             'diameter': '13500',
             'gravity': '1',
             'name': 'Chandrila',
             'orbital_period': '368',
             'population': '1200000000',
             'residents': ['http://swapi.co/api/people/28/'],
             'rotation_period': '20',
             'surface_water': '40',
             'terrain': 'plains, forests'},
            {'climate': 'superheated',
             'diameter': '12780',
             'gravity': '1',
             'name': 'Sullust',
             'orbital_period': '263',
             'population': '18500000000',
             'residents': ['http://swapi.co/api/people/31/'],
             'rotation_period': '20',
             'surface_water': '5',
             'terrain': 'mountains, volcanoes, rocky deserts'},
            {'climate': 'temperate',
             'diameter': '7900',
             'gravity': '1',
             'name': 'Toydaria',
             'orbital_period': '184',
             'population': '11000000',
             'residents': ['http://swapi.co/api/people/40/'],
             'rotation_period': '21',
             'surface_water': 'unknown',
             'terrain': 'swamps, lakes'},
            {'climate': 'arid, temperate, tropical',
             'diameter': '18880',
             'gravity': '1.56',
             'name': 'Malastare',
             'orbital_period': '201',
             'population': '2000000000',
             'residents': ['http://swapi.co/api/people/41/'],
             'rotation_period': '26',
             'surface_water': 'unknown',
             'terrain': 'swamps, deserts, jungles, mountains'},
            {'climate': 'temperate',
             'diameter': '10480',
             'gravity': '0.9',
             'name': 'Dathomir',
             'orbital_period': '491',
             'population': '5200',
             'residents': ['http://swapi.co/api/people/44/'],
             'rotation_period': '24',
             'surface_water': 'unknown',
             'terrain': 'forests, deserts, savannas'},
            {'climate': 'temperate, arid, subartic',
             'diameter': '10600',
             'gravity': '1',
             'name': 'Ryloth',
             'orbital_period': '305',
             'population': '1500000000',
             'residents': ['http://swapi.co/api/people/45/',
                           'http://swapi.co/api/people/46/'],
             'rotation_period': '30',
             'surface_water': '5',
             'terrain': 'mountains, valleys, deserts, tundra'},
            {'climate': 'unknown',
             'diameter': 'unknown',
             'gravity': 'unknown',
             'name': 'Aleen Minor',
             'orbital_period': 'unknown',
             'population': 'unknown',
             'residents': ['http://swapi.co/api/people/47/'],
             'rotation_period': 'unknown',
             'surface_water': 'unknown',
             'terrain': 'unknown'},
            {'climate': 'temperate, artic',
             'diameter': '14900',
             'gravity': '1',
             'name': 'Vulpter',
             'orbital_period': '391',
             'population': '421000000',
             'residents': ['http://swapi.co/api/people/48/'],
             'rotation_period': '22',
             'surface_water': 'unknown',
             'terrain': 'urban, barren'},
            {'climate': 'unknown',
             'diameter': 'unknown',
             'gravity': 'unknown',
             'name': 'Troiken',
             'orbital_period': 'unknown',
             'population': 'unknown',
             'residents': ['http://swapi.co/api/people/49/'],
             'rotation_period': 'unknown',
             'surface_water': 'unknown',
             'terrain': 'desert, tundra, rainforests, mountains'},
            {'climate': 'unknown',
             'diameter': '12190',
             'gravity': 'unknown',
             'name': 'Tund',
             'orbital_period': '1770',
             'population': '0',
             'residents': ['http://swapi.co/api/people/50/'],
             'rotation_period': '48',
             'surface_water': 'unknown',
             'terrain': 'barren, ash'},
            {'climate': 'temperate',
             'diameter': '10120',
             'gravity': '0.98',
             'name': 'Haruun Kal',
             'orbital_period': '383',
             'population': '705300',
             'residents': ['http://swapi.co/api/people/51/'],
             'rotation_period': '25',
             'surface_water': 'unknown',
             'terrain': 'toxic cloudsea, plateaus, volcanoes'},
            {'climate': 'temperate',
             'diameter': 'unknown',
             'gravity': '1',
             'name': 'Cerea',
             'orbital_period': '386',
             'population': '450000000',
             'residents': ['http://swapi.co/api/people/52/'],
             'rotation_period': '27',
             'surface_water': '20',
             'terrain': 'verdant'},
            {'climate': 'tropical, temperate',
             'diameter': '15600',
             'gravity': '1',
             'name': 'Glee Anselm',
             'orbital_period': '206',
             'population': '500000000',
             'residents': ['http://swapi.co/api/people/53/'],
             'rotation_period': '33',
             'surface_water': '80',
             'terrain': 'lakes, islands, swamps, seas'},
            {'climate': 'unknown',
             'diameter': 'unknown',
             'gravity': 'unknown',
             'name': 'Iridonia',
             'orbital_period': '413',
             'population': 'unknown',
             'residents': ['http://swapi.co/api/people/54/'],
             'rotation_period': '29',
             'surface_water': 'unknown',
             'terrain': 'rocky canyons, acid pools'},
            {'climate': 'unknown',
             'diameter': 'unknown',
             'gravity': 'unknown',
             'name': 'Tholoth',
             'orbital_period': 'unknown',
             'population': 'unknown',
             'residents': [],
             'rotation_period': 'unknown',
             'surface_water': 'unknown',
             'terrain': 'unknown'},
            {'climate': 'arid, rocky, windy',
             'diameter': 'unknown',
             'gravity': '1',
             'name': 'Iktotch',
             'orbital_period': '481',
             'population': 'unknown',
             'residents': ['http://swapi.co/api/people/56/'],
             'rotation_period': '22',
             'surface_water': 'unknown',
             'terrain': 'rocky'},
            {'climate': 'unknown',
             'diameter': 'unknown',
             'gravity': 'unknown',
             'name': 'Quermia',
             'orbital_period': 'unknown',
             'population': 'unknown',
             'residents': ['http://swapi.co/api/people/57/'],
             'rotation_period': 'unknown',
             'surface_water': 'unknown',
             'terrain': 'unknown'},
            {'climate': 'temperate',
             'diameter': '13400',
             'gravity': '1',
             'name': 'Dorin',
             'orbital_period': '409',
             'population': 'unknown',
             'residents': ['http://swapi.co/api/people/58/'],
             'rotation_period': '22',
             'surface_water': 'unknown',
             'terrain': 'unknown'},
            {'climate': 'temperate',
             'diameter': 'unknown',
             'gravity': '1',
             'name': 'Champala',
             'orbital_period': '318',
             'population': '3500000000',
             'residents': ['http://swapi.co/api/people/59/'],
             'rotation_period': '27',
             'surface_water': 'unknown',
             'terrain': 'oceans, rainforests, plateaus'},
            {'climate': 'unknown',
             'diameter': 'unknown',
             'gravity': 'unknown',
             'name': 'Mirial',
             'orbital_period': 'unknown',
             'population': 'unknown',
             'residents': ['http://swapi.co/api/people/64/',
                           'http://swapi.co/api/people/65/'],
             'rotation_period': 'unknown',
             'surface_water': 'unknown',
             'terrain': 'deserts'},
            {'climate': 'unknown',
             'diameter': 'unknown',
             'gravity': 'unknown',
             'name': 'Serenno',
             'orbital_period': 'unknown',
             'population': 'unknown',
             'residents': ['http://swapi.co/api/people/67/'],
             'rotation_period': 'unknown',
             'surface_water': 'unknown',
             'terrain': 'rainforests, rivers, mountains'},
            {'climate': 'unknown',
             'diameter': 'unknown',
             'gravity': 'unknown',
             'name': 'Concord Dawn',
             'orbital_period': 'unknown',
             'population': 'unknown',
             'residents': ['http://swapi.co/api/people/69/'],
             'rotation_period': 'unknown',
             'surface_water': 'unknown',
             'terrain': 'jungles, forests, deserts'},
            {'climate': 'unknown',
             'diameter': 'unknown',
             'gravity': 'unknown',
             'name': 'Zolan',
             'orbital_period': 'unknown',
             'population': 'unknown',
             'residents': ['http://swapi.co/api/people/70/'],
             'rotation_period': 'unknown',
             'surface_water': 'unknown',
             'terrain': 'unknown'},
            {'climate': 'frigid',
             'diameter': 'unknown',
             'gravity': 'unknown',
             'name': 'Ojom',
             'orbital_period': 'unknown',
             'population': '500000000',
             'residents': ['http://swapi.co/api/people/71/'],
             'rotation_period': 'unknown',
             'surface_water': '100',
             'terrain': 'oceans, glaciers'},
            {'climate': 'temperate',
             'diameter': 'unknown',
             'gravity': '1',
             'name': 'Skako',
             'orbital_period': '384',
             'population': '500000000000',
             'residents': ['http://swapi.co/api/people/76/'],
             'rotation_period': '27',
             'surface_water': 'unknown',
             'terrain': 'urban, vines'},
            {'climate': 'temperate',
             'diameter': '13800',
             'gravity': '1',
             'name': 'Muunilinst',
             'orbital_period': '412',
             'population': '5000000000',
             'residents': ['http://swapi.co/api/people/77/'],
             'rotation_period': '28',
             'surface_water': '25',
             'terrain': 'plains, forests, hills, mountains'},
            {'climate': 'temperate',
             'diameter': 'unknown',
             'gravity': '1',
             'name': 'Shili',
             'orbital_period': 'unknown',
             'population': 'unknown',
             'residents': ['http://swapi.co/api/people/78/'],
             'rotation_period': 'unknown',
             'surface_water': 'unknown',
             'terrain': 'cities, savannahs, seas, plains'},
            {'climate': 'arid, temperate, tropical',
             'diameter': '13850',
             'gravity': '1',
             'name': 'Kalee',
             'orbital_period': '378',
             'population': '4000000000',
             'residents': ['http://swapi.co/api/people/79/'],
             'rotation_period': '23',
             'surface_water': 'unknown',
             'terrain': 'rainforests, cliffs, canyons, seas'},
            {'climate': 'unknown',
             'diameter': 'unknown',
             'gravity': 'unknown',
             'name': 'Umbara',
             'orbital_period': 'unknown',
             'population': 'unknown',
             'residents': ['http://swapi.co/api/people/82/'],
             'rotation_period': 'unknown',
             'surface_water': 'unknown',
             'terrain': 'unknown'},
            {'climate': 'unknown',
             'diameter': 'unknown',
             'gravity': 'unknown',
             'name': 'Jakku',
             'orbital_period': 'unknown',
             'population': 'unknown',
             'residents': [],
             'rotation_period': 'unknown',
             'surface_water': 'unknown',
             'terrain': 'deserts'}]
    return data
