#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""Star Wars data file."""


def get_star_wars_data():
    """Get Star Wars data."""
    sw_data = [
        {
            'birth_year': '19BBY',
            'created': '2014-12-09T13:50:51.644000Z',
            'eye_color': 'blue',
            'gender': 'male',
            'hair_color': 'blond',
            'height': '172',
            'mass': '77',
            'name': 'Luke Skywalker',
            'skin_color': 'fair'},
        {
            'birth_year': '112BBY',
            'created': '2014-12-10T15:10:51.357000Z',
            'eye_color': 'yellow',
            'gender': 'n/a',
            'hair_color': 'n/a',
            'height': '167',
            'mass': '75',
            'name': 'C-3PO',
            'skin_color': 'gold'},
        {
            'birth_year': '33BBY',
            'created': '2014-12-10T15:11:50.376000Z',
            'eye_color': 'red',
            'gender': 'n/a',
            'hair_color': 'n/a',
            'height': '96',
            'mass': '32',
            'name': 'R2-D2',
            'skin_color': 'white, blue'},
        {
            'birth_year': '41.9BBY',
            'created': '2014-12-10T15:18:20.704000Z',
            'eye_color': 'yellow',
            'gender': 'male',
            'hair_color': 'none',
            'height': '202',
            'mass': '136',
            'name': 'Darth Vader',
            'skin_color': 'white'},
        {
            'birth_year': '19BBY',
            'created': '2014-12-10T15:20:09.791000Z',
            'eye_color': 'brown',
            'gender': 'female',
            'hair_color': 'brown',
            'height': '150',
            'mass': '49',
            'name': 'Leia Organa',
            'skin_color': 'light'},
        {
            'birth_year': '52BBY',
            'created': '2014-12-10T15:52:14.024000Z',
            'eye_color': 'blue',
            'gender': 'male',
            'hair_color': 'brown, grey',
            'height': '178',
            'mass': '120',
            'name': 'Owen Lars',
            'skin_color': 'light'},
        {
            'birth_year': '47BBY',
            'created': '2014-12-10T15:53:41.121000Z',
            'eye_color': 'blue',
            'gender': 'female',
            'hair_color': 'brown',
            'height': '165',
            'mass': '75',
            'name': 'Beru Whitesun lars',
            'skin_color': 'light'},
        {
            'birth_year': 'unknown',
            'created': '2014-12-10T15:57:50.959000Z',
            'eye_color': 'red',
            'gender': 'n/a',
            'hair_color': 'n/a',
            'height': '97',
            'mass': '32',
            'name': 'R5-D4',
            'skin_color': 'white, red'},
        {
            'birth_year': '24BBY',
            'created': '2014-12-10T15:59:50.509000Z',
            'eye_color': 'brown',
            'gender': 'male',
            'hair_color': 'black',
            'height': '183',
            'mass': '84',
            'name': 'Biggs Darklighter',
            'skin_color': 'light'},
        {
            'birth_year': '57BBY',
            'created': '2014-12-10T16:16:29.192000Z',
            'eye_color': 'blue-gray',
            'gender': 'male',
            'hair_color': 'auburn, white',
            'height': '182',
            'mass': '77',
            'name': 'Obi-Wan Kenobi',
            'skin_color': 'fair'},
        {
            'birth_year': '41.9BBY',
            'created': '2014-12-10T16:20:44.310000Z',
            'eye_color': 'blue',
            'gender': 'male',
            'hair_color': 'blond',
            'height': '188',
            'mass': '84',
            'name': 'Anakin Skywalker',
            'skin_color': 'fair'},
        {
            'birth_year': '64BBY',
            'created': '2014-12-10T16:26:56.138000Z',
            'eye_color': 'blue',
            'gender': 'male',
            'hair_color': 'auburn, grey',
            'height': '180',
            'mass': 'unknown',
            'name': 'Wilhuff Tarkin',
            'skin_color': 'fair'},
        {
            'birth_year': '200BBY',
            'created': '2014-12-10T16:42:45.066000Z',
            'eye_color': 'blue',
            'gender': 'male',
            'hair_color': 'brown',
            'height': '228',
            'mass': '112',
            'name': 'Chewbacca',
            'skin_color': 'unknown'},
        {
            'birth_year': '29BBY',
            'created': '2014-12-10T16:49:14.582000Z',
            'eye_color': 'brown',
            'gender': 'male',
            'hair_color': 'brown',
            'height': '180',
            'mass': '80',
            'name': 'Han Solo',
            'skin_color': 'fair'},
        {
            'birth_year': '44BBY',
            'created': '2014-12-10T17:03:30.334000Z',
            'eye_color': 'black',
            'gender': 'male',
            'hair_color': 'n/a',
            'height': '173',
            'mass': '74',
            'name': 'Greedo',
            'skin_color': 'green'},
        {
            'birth_year': '600BBY',
            'created': '2014-12-10T17:11:31.638000Z',
            'eye_color': 'orange',
            'gender': 'hermaphrodite',
            'hair_color': 'n/a',
            'height': '175',
            'mass': '1,358',
            'name': 'Jabba Desilijic Tiure',
            'skin_color': 'green-tan, brown'},
        {
            'birth_year': '21BBY',
            'created': '2014-12-12T11:08:06.469000Z',
            'eye_color': 'hazel',
            'gender': 'male',
            'hair_color': 'brown',
            'height': '170',
            'mass': '77',
            'name': 'Wedge Antilles',
            'skin_color': 'fair'},
        {
            'birth_year': 'unknown',
            'created': '2014-12-12T11:16:56.569000Z',
            'eye_color': 'blue',
            'gender': 'male',
            'hair_color': 'brown',
            'height': '180',
            'mass': '110',
            'name': 'Jek Tono Porkins',
            'skin_color': 'fair'},
        {
            'birth_year': '896BBY',
            'created': '2014-12-15T12:26:01.042000Z',
            'eye_color': 'brown',
            'gender': 'male',
            'hair_color': 'white',
            'height': '66',
            'mass': '17',
            'name': 'Yoda',
            'skin_color': 'green'},
        {
            'birth_year': '82BBY',
            'created': '2014-12-15T12:48:05.971000Z',
            'eye_color': 'yellow',
            'gender': 'male',
            'hair_color': 'grey',
            'height': '170',
            'mass': '75',
            'name': 'Palpatine',
            'skin_color': 'pale'},
        {
            'birth_year': '31.5BBY',
            'created': '2014-12-15T12:49:32.457000Z',
            'eye_color': 'brown',
            'gender': 'male',
            'hair_color': 'black',
            'height': '183',
            'mass': '78.2',
            'name': 'Boba Fett',
            'skin_color': 'fair'},
        {
            'birth_year': '15BBY',
            'created': '2014-12-15T12:51:10.076000Z',
            'eye_color': 'red',
            'gender': 'none',
            'hair_color': 'none',
            'height': '200',
            'mass': '140',
            'name': 'IG-88',
            'skin_color': 'metal'},
        {
            'birth_year': '53BBY',
            'created': '2014-12-15T12:53:49.297000Z',
            'eye_color': 'red',
            'gender': 'male',
            'hair_color': 'none',
            'height': '190',
            'mass': '113',
            'name': 'Bossk',
            'skin_color': 'green'},
        {
            'birth_year': '31BBY',
            'created': '2014-12-15T12:56:32.683000Z',
            'eye_color': 'brown',
            'gender': 'male',
            'hair_color': 'black',
            'height': '177',
            'mass': '79',
            'name': 'Lando Calrissian',
            'skin_color': 'dark'},
        {
            'birth_year': '37BBY',
            'created': '2014-12-15T13:01:57.178000Z',
            'eye_color': 'blue',
            'gender': 'male',
            'hair_color': 'none',
            'height': '175',
            'mass': '79',
            'name': 'Lobot',
            'skin_color': 'light'},
        {
            'birth_year': '41BBY',
            'created': '2014-12-18T11:07:50.584000Z',
            'eye_color': 'orange',
            'gender': 'male',
            'hair_color': 'none',
            'height': '180',
            'mass': '83',
            'name': 'Ackbar',
            'skin_color': 'brown mottle'},
        {
            'birth_year': '48BBY',
            'created': '2014-12-18T11:12:38.895000Z',
            'eye_color': 'blue',
            'gender': 'female',
            'hair_color': 'auburn',
            'height': '150',
            'mass': 'unknown',
            'name': 'Mon Mothma',
            'skin_color': 'fair'},
        {
            'birth_year': 'unknown',
            'created': '2014-12-18T11:16:33.020000Z',
            'eye_color': 'brown',
            'gender': 'male',
            'hair_color': 'brown',
            'height': 'unknown',
            'mass': 'unknown',
            'name': 'Arvel Crynyd',
            'skin_color': 'fair'},
        {
            'birth_year': '8BBY',
            'created': '2014-12-18T11:21:58.954000Z',
            'eye_color': 'brown',
            'gender': 'male',
            'hair_color': 'brown',
            'height': '88',
            'mass': '20',
            'name': 'Wicket Systri Warrick',
            'skin_color': 'brown'},
        {
            'birth_year': 'unknown',
            'created': '2014-12-18T11:26:18.541000Z',
            'eye_color': 'black',
            'gender': 'male',
            'hair_color': 'none',
            'height': '160',
            'mass': '68',
            'name': 'Nien Nunb',
            'skin_color': 'grey'},
        {
            'birth_year': '92BBY',
            'created': '2014-12-19T16:54:53.618000Z',
            'eye_color': 'blue',
            'gender': 'male',
            'hair_color': 'brown',
            'height': '193',
            'mass': '89',
            'name': 'Qui-Gon Jinn',
            'skin_color': 'fair'},
        {
            'birth_year': 'unknown',
            'created': '2014-12-19T17:05:57.357000Z',
            'eye_color': 'red',
            'gender': 'male',
            'hair_color': 'none',
            'height': '191',
            'mass': '90',
            'name': 'Nute Gunray',
            'skin_color': 'mottled green'},
        {
            'birth_year': '91BBY',
            'created': '2014-12-19T17:21:45.915000Z',
            'eye_color': 'blue',
            'gender': 'male',
            'hair_color': 'blond',
            'height': '170',
            'mass': 'unknown',
            'name': 'Finis Valorum',
            'skin_color': 'fair'},
        {
            'birth_year': '46BBY',
            'created': '2014-12-19T17:28:26.926000Z',
            'eye_color': 'brown',
            'gender': 'female',
            'hair_color': 'brown',
            'height': '165',
            'mass': '45',
            'name': 'Padmé Amidala',
            'skin_color': 'light'},
        {
            'birth_year': '52BBY',
            'created': '2014-12-19T17:29:32.489000Z',
            'eye_color': 'orange',
            'gender': 'male',
            'hair_color': 'none',
            'height': '196',
            'mass': '66',
            'name': 'Jar Jar Binks',
            'skin_color': 'orange'},
        {
            'birth_year': 'unknown',
            'created': '2014-12-19T17:32:56.741000Z',
            'eye_color': 'orange',
            'gender': 'male',
            'hair_color': 'none',
            'height': '224',
            'mass': '82',
            'name': 'Roos Tarpals',
            'skin_color': 'grey'},
        {
            'birth_year': 'unknown',
            'created': '2014-12-19T17:33:38.909000Z',
            'eye_color': 'orange',
            'gender': 'male',
            'hair_color': 'none',
            'height': '206',
            'mass': 'unknown',
            'name': 'Rugor Nass',
            'skin_color': 'green'},
        {
            'birth_year': 'unknown',
            'created': '2014-12-19T17:45:01.522000Z',
            'eye_color': 'blue',
            'gender': 'male',
            'hair_color': 'brown',
            'height': '183',
            'mass': 'unknown',
            'name': 'Ric Olié',
            'skin_color': 'fair'},
        {
            'birth_year': 'unknown',
            'created': '2014-12-19T17:48:54.647000Z',
            'eye_color': 'yellow',
            'gender': 'male',
            'hair_color': 'black',
            'height': '137',
            'mass': 'unknown',
            'name': 'Watto',
            'skin_color': 'blue, grey'},
        {
            'birth_year': 'unknown',
            'created': '2014-12-19T17:53:02.586000Z',
            'eye_color': 'orange',
            'gender': 'male',
            'hair_color': 'none',
            'height': '112',
            'mass': '40',
            'name': 'Sebulba',
            'skin_color': 'grey, red'},
        {
            'birth_year': '62BBY',
            'created': '2014-12-19T17:55:43.348000Z',
            'eye_color': 'brown',
            'gender': 'male',
            'hair_color': 'black',
            'height': '183',
            'mass': 'unknown',
            'name': 'Quarsh Panaka',
            'skin_color': 'dark'},
        {
            'birth_year': '72BBY',
            'created': '2014-12-19T17:57:41.191000Z',
            'eye_color': 'brown',
            'gender': 'female',
            'hair_color': 'black',
            'height': '163',
            'mass': 'unknown',
            'name': 'Shmi Skywalker',
            'skin_color': 'fair'},
        {
            'birth_year': '54BBY',
            'created': '2014-12-19T18:00:41.929000Z',
            'eye_color': 'yellow',
            'gender': 'male',
            'hair_color': 'none',
            'height': '175',
            'mass': '80',
            'name': 'Darth Maul',
            'skin_color': 'red'},
        {
            'birth_year': 'unknown',
            'created': '2014-12-20T09:47:02.512000Z',
            'eye_color': 'pink',
            'gender': 'male',
            'hair_color': 'none',
            'height': '180',
            'mass': 'unknown',
            'name': 'Bib Fortuna',
            'skin_color': 'pale'},
        {
            'birth_year': '48BBY',
            'created': '2014-12-20T09:48:01.172000Z',
            'eye_color': 'hazel',
            'gender': 'female',
            'hair_color': 'none',
            'height': '178',
            'mass': '55',
            'name': 'Ayla Secura',
            'skin_color': 'blue'},
        {
            'birth_year': 'unknown',
            'created': '2014-12-20T09:53:15.086000Z',
            'eye_color': 'unknown',
            'gender': 'male',
            'hair_color': 'none',
            'height': '79',
            'mass': '15',
            'name': 'Ratts Tyerell',
            'skin_color': 'grey, blue'},
        {
            'birth_year': 'unknown',
            'created': '2014-12-20T09:57:31.858000Z',
            'eye_color': 'yellow',
            'gender': 'male',
            'hair_color': 'none',
            'height': '94',
            'mass': '45',
            'name': 'Dud Bolt',
            'skin_color': 'blue, grey'},
        {
            'birth_year': 'unknown',
            'created': '2014-12-20T10:02:12.223000Z',
            'eye_color': 'black',
            'gender': 'male',
            'hair_color': 'none',
            'height': '122',
            'mass': 'unknown',
            'name': 'Gasgano',
            'skin_color': 'white, blue'},
        {
            'birth_year': 'unknown',
            'created': '2014-12-20T10:08:33.777000Z',
            'eye_color': 'orange',
            'gender': 'male',
            'hair_color': 'none',
            'height': '163',
            'mass': '65',
            'name': 'Ben Quadinaros',
            'skin_color': 'grey, green, yellow'},
        {'birth_year': '72BBY',
         'created': '2014-12-20T10:12:30.846000Z',
         'eye_color': 'brown',
         'gender': 'male',
         'hair_color': 'none',
         'height': '188',
         'mass': '84',
         'name': 'Mace Windu',
         'skin_color': 'dark'},
        {'birth_year': '92BBY',
         'created': '2014-12-20T10:15:32.293000Z',
         'eye_color': 'yellow',
         'gender': 'male',
         'hair_color': 'white',
         'height': '198',
         'mass': '82',
         'name': 'Ki-Adi-Mundi',
         'skin_color': 'pale'},
        {'birth_year': 'unknown',
         'created': '2014-12-20T10:18:57.202000Z',
         'eye_color': 'black',
         'gender': 'male',
         'hair_color': 'none',
         'height': '196',
         'mass': '87',
         'name': 'Kit Fisto',
         'skin_color': 'green'},
        {'birth_year': 'unknown',
         'created': '2014-12-20T10:26:47.902000Z',
         'eye_color': 'brown',
         'gender': 'male',
         'hair_color': 'black',
         'height': '171',
         'mass': 'unknown',
         'name': 'Eeth Koth',
         'skin_color': 'brown'},
        {'birth_year': 'unknown',
         'created': '2014-12-20T10:29:11.661000Z',
         'eye_color': 'blue',
         'gender': 'female',
         'hair_color': 'none',
         'height': '184',
         'mass': '50',
         'name': 'Adi Gallia',
         'skin_color': 'dark'},
        {'birth_year': 'unknown',
         'created': '2014-12-20T10:32:11.669000Z',
         'eye_color': 'orange',
         'gender': 'male',
         'hair_color': 'none',
         'height': '188',
         'mass': 'unknown',
         'name': 'Saesee Tiin',
         'skin_color': 'pale'},
        {'birth_year': 'unknown',
         'created': '2014-12-20T10:34:48.725000Z',
         'eye_color': 'yellow',
         'gender': 'male',
         'hair_color': 'none',
         'height': '264',
         'mass': 'unknown',
         'name': 'Yarael Poof',
         'skin_color': 'white'},
        {'birth_year': '22BBY',
         'created': '2014-12-20T10:49:19.859000Z',
         'eye_color': 'black',
         'gender': 'male',
         'hair_color': 'none',
         'height': '188',
         'mass': '80',
         'name': 'Plo Koon',
         'skin_color': 'orange'},
        {'birth_year': 'unknown',
         'created': '2014-12-20T10:53:26.457000Z',
         'eye_color': 'blue',
         'gender': 'male',
         'hair_color': 'none',
         'height': '196',
         'mass': 'unknown',
         'name': 'Mas Amedda',
         'skin_color': 'blue'},
        {'birth_year': 'unknown',
         'created': '2014-12-20T11:10:10.381000Z',
         'eye_color': 'brown',
         'gender': 'male',
         'hair_color': 'black',
         'height': '185',
         'mass': '85',
         'name': 'Gregar Typho',
         'skin_color': 'dark'},
        {'birth_year': 'unknown',
         'created': '2014-12-20T11:11:39.630000Z',
         'eye_color': 'brown',
         'gender': 'female',
         'hair_color': 'brown',
         'height': '157',
         'mass': 'unknown',
         'name': 'Cordé',
         'skin_color': 'light'},
        {'birth_year': '82BBY',
         'created': '2014-12-20T15:59:03.958000Z',
         'eye_color': 'blue',
         'gender': 'male',
         'hair_color': 'brown',
         'height': '183',
         'mass': 'unknown',
         'name': 'Cliegg Lars',
         'skin_color': 'fair'},
        {'birth_year': 'unknown',
         'created': '2014-12-20T16:40:43.977000Z',
         'eye_color': 'yellow',
         'gender': 'male',
         'hair_color': 'none',
         'height': '183',
         'mass': '80',
         'name': 'Poggle the Lesser',
         'skin_color': 'green'},
        {'birth_year': '58BBY',
         'created': '2014-12-20T16:45:53.668000Z',
         'eye_color': 'blue',
         'gender': 'female',
         'hair_color': 'black',
         'height': '170',
         'mass': '56.2',
         'name': 'Luminara Unduli',
         'skin_color': 'yellow'},
        {'birth_year': '40BBY',
         'created': '2014-12-20T16:46:40.440000Z',
         'eye_color': 'blue',
         'gender': 'female',
         'hair_color': 'black',
         'height': '166',
         'mass': '50',
         'name': 'Barriss Offee',
         'skin_color': 'yellow'},
        {'birth_year': 'unknown',
         'created': '2014-12-20T16:49:14.640000Z',
         'eye_color': 'brown',
         'gender': 'female',
         'hair_color': 'brown',
         'height': '165',
         'mass': 'unknown',
         'name': 'Dormé',
         'skin_color': 'light'},
        {'birth_year': '102BBY',
         'created': '2014-12-20T16:52:14.726000Z',
         'eye_color': 'brown',
         'gender': 'male',
         'hair_color': 'white',
         'height': '193',
         'mass': '80',
         'name': 'Dooku',
         'skin_color': 'fair'},
        {'birth_year': '67BBY',
         'created': '2014-12-20T16:53:08.575000Z',
         'eye_color': 'brown',
         'gender': 'male',
         'hair_color': 'black',
         'height': '191',
         'mass': 'unknown',
         'name': 'Bail Prestor Organa',
         'skin_color': 'tan'},
        {'birth_year': '66BBY',
         'created': '2014-12-20T16:54:41.620000Z',
         'eye_color': 'brown',
         'gender': 'male',
         'hair_color': 'black',
         'height': '183',
         'mass': '79',
         'name': 'Jango Fett',
         'skin_color': 'tan'},
        {'birth_year': 'unknown',
         'created': '2014-12-20T16:57:44.471000Z',
         'eye_color': 'yellow',
         'gender': 'female',
         'hair_color': 'blonde',
         'height': '168',
         'mass': '55',
         'name': 'Zam Wesell',
         'skin_color': 'fair, green, yellow'},
        {'birth_year': 'unknown',
         'created': '2014-12-20T17:28:27.248000Z',
         'eye_color': 'yellow',
         'gender': 'male',
         'hair_color': 'none',
         'height': '198',
         'mass': '102',
         'name': 'Dexter Jettster',
         'skin_color': 'brown'},
        {'birth_year': 'unknown',
         'created': '2014-12-20T17:30:50.416000Z',
         'eye_color': 'black',
         'gender': 'male',
         'hair_color': 'none',
         'height': '229',
         'mass': '88',
         'name': 'Lama Su',
         'skin_color': 'grey'},
        {'birth_year': 'unknown',
         'created': '2014-12-20T17:31:21.195000Z',
         'eye_color': 'black',
         'gender': 'female',
         'hair_color': 'none',
         'height': '213',
         'mass': 'unknown',
         'name': 'Taun We',
         'skin_color': 'grey'},
        {'birth_year': 'unknown',
         'created': '2014-12-20T17:32:51.996000Z',
         'eye_color': 'blue',
         'gender': 'female',
         'hair_color': 'white',
         'height': '167',
         'mass': 'unknown',
         'name': 'Jocasta Nu',
         'skin_color': 'fair'},
        {'birth_year': 'unknown',
         'created': '2014-12-20T17:43:36.409000Z',
         'eye_color': 'red, blue',
         'gender': 'female',
         'hair_color': 'none',
         'height': '96',
         'mass': 'unknown',
         'name': 'R4-P17',
         'skin_color': 'silver, red'},
        {'birth_year': 'unknown',
         'created': '2014-12-20T17:53:52.607000Z',
         'eye_color': 'unknown',
         'gender': 'male',
         'hair_color': 'none',
         'height': '193',
         'mass': '48',
         'name': 'Wat Tambor',
         'skin_color': 'green, grey'},
        {'birth_year': 'unknown',
         'created': '2014-12-20T17:58:17.049000Z',
         'eye_color': 'gold',
         'gender': 'male',
         'hair_color': 'none',
         'height': '191',
         'mass': 'unknown',
         'name': 'San Hill',
         'skin_color': 'grey'},
        {'birth_year': 'unknown',
         'created': '2014-12-20T18:44:01.103000Z',
         'eye_color': 'black',
         'gender': 'female',
         'hair_color': 'none',
         'height': '178',
         'mass': '57',
         'name': 'Shaak Ti',
         'skin_color': 'red, blue, white'},
        {'birth_year': 'unknown',
         'created': '2014-12-20T19:43:53.348000Z',
         'eye_color': 'green, yellow',
         'gender': 'male',
         'hair_color': 'none',
         'height': '216',
         'mass': '159',
         'name': 'Grievous',
         'skin_color': 'brown, white'
         }
    ]

    return sw_data
